import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "@/components/NextAuthProvider";
import { ReactNode } from "react";
import { Session } from "next-auth";
import localFont from "next/font/local";
import ReactQuery from "@/components/ReactQuery";
import { Providers } from "./providers";
import PrelineScript from "@/components/ PrelineScript";

const poppins = localFont({
  src: [
    {
      path: "../public/fonts/Poppins-Light.ttf",
      weight: "300",
      style: "light",
    },
    {
      path: "../public/fonts/Poppins-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Poppins-Medium.ttf",
      weight: "500",
      style: "medium",
    },
    {
      path: "../public/fonts/Poppins-SemiBold.ttf",
      weight: "600",
      style: "semibold",
    },
    {
      path: "../public/fonts/Poppins-Bold.ttf",
      weight: "700",
      style: "bold",
    },
  ],
});

interface NextAuthProps {
  children: ReactNode;
  session: Session | null | undefined;
}

export const metadata: Metadata = {
  title: "EduCommunity",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }: NextAuthProps) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <NextAuthProvider session={session}>
          <ReactQuery>
            <Providers>{children} </Providers>
          </ReactQuery>
        </NextAuthProvider>
      </body>
      <PrelineScript />
    </html>
  );
}
